// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetoJobs.Contexts;

#nullable disable

namespace projetoJobs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212002014_CreateCandidaturaTable")]
    partial class CreateCandidaturaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projetoJobs.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResumoPerfil")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Senha")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id")
                        .HasName("PK__Candidat__3213E83FFBA023F9");

                    b.HasIndex(new[] { "Cpf" }, "UQ__Candidat__C1F897317D497801")
                        .IsUnique()
                        .HasFilter("[CPF] IS NOT NULL");

                    b.ToTable("Candidato", (string)null);
                });

            modelBuilder.Entity("projetoJobs.Models.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("datetime");

                    b.Property<int>("VagaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("VagaId");

                    b.ToTable("Candidatura", (string)null);
                });

            modelBuilder.Entity("projetoJobs.Models.Curriculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<int>("CandidatosId")
                        .HasColumnType("int")
                        .HasColumnName("Candidatos_id");

                    b.Property<DateTime?>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_envio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<int>("VagasId")
                        .HasColumnType("int")
                        .HasColumnName("Vagas_id");

                    b.HasKey("Id")
                        .HasName("PK__Curricul__3213E83F115FFA98");

                    b.HasIndex("CandidatosId");

                    b.HasIndex("VagasId");

                    b.ToTable("Curriculo", (string)null);
                });

            modelBuilder.Entity("projetoJobs.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Descricao")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id")
                        .HasName("PK__Empresa__3213E83F2D1F8529");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("projetoJobs.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescricaoVaga")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("EmpresasId")
                        .HasColumnType("int")
                        .HasColumnName("Empresas_id");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NivelExperiencia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeVaga")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TipoContrato")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Vaga__3213E83FB5EA088B");

                    b.HasIndex("EmpresasId");

                    b.ToTable("Vaga", (string)null);
                });

            modelBuilder.Entity("projetoJobs.Models.Candidatura", b =>
                {
                    b.HasOne("projetoJobs.Models.Candidato", "Candidato")
                        .WithMany("Candidaturas")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projetoJobs.Models.Vaga", "Vaga")
                        .WithMany("Candidaturas")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("projetoJobs.Models.Curriculo", b =>
                {
                    b.HasOne("projetoJobs.Models.Candidato", "Candidato")
                        .WithMany("Curriculos")
                        .HasForeignKey("CandidatosId")
                        .IsRequired()
                        .HasConstraintName("FK__Curriculo__Candi__403A8C7D");

                    b.HasOne("projetoJobs.Models.Vaga", "Vaga")
                        .WithMany("Curriculos")
                        .HasForeignKey("VagasId")
                        .IsRequired()
                        .HasConstraintName("FK__Curriculo__Vagas__412EB0B6");

                    b.Navigation("Candidato");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("projetoJobs.Models.Vaga", b =>
                {
                    b.HasOne("projetoJobs.Models.Empresa", "Empresas")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresasId")
                        .IsRequired()
                        .HasConstraintName("FK__Vaga__Empresas_i__3C69FB99");

                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("projetoJobs.Models.Candidato", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Curriculos");
                });

            modelBuilder.Entity("projetoJobs.Models.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("projetoJobs.Models.Vaga", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Curriculos");
                });
#pragma warning restore 612, 618
        }
    }
}
